name: pyincore
channels:
  - conda-forge
  - defaults
dependencies:
  - ipopt>=3.11
  - fiona>=1.8.4
  - folium
  - geopandas>=0.6.1
  - matplotlib>=2.1.0
  - networkx>=2.2
  - numpy>=1.16.6,<2.0a0
  - pandas>=0.24.1
  - pycodestyle>=2.6.0
  - pyomo>=5.6
  - pyproj>=1.9.6
  - pytest>=3.9.0
  - python-jose>=3.0
  - rasterio>=1.0.18
  - rtree>=0.8.3
  - scipy>=1.2.0
  - shapely>=1.6.4.post1wntr
  - wntr>=0.1.6
